### ISSUE TITLE
Docker installations cannot write var/fred/STDERR.log

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/fred#13]
Right after installation on a docker based system, fred complains not being able to open /opt/otobo/var/fred/STDERR.log (be aware, that the message about "/var/fred/STDERR.log" is hardcoded, /opt/otobo is prepended correctly in the actually used path). After creating the directory and touching the file, the message vanishes, but at least in a quick test, the file was still not written to. (The docker environment is most likely the reason, but I cannot fully exclude that it is something with 10.1.5.)

**Comment by bschmalhofer** [comment]
Hi Sven,
I tried it with a fresh OTOBO installation in Docker and a fresh built of Fred. In this scenario everything looked fine. The directory _/opt/otobo/var/fred_ was apparently created when _Kernel/Config/Files/Fred.pm_ was loaded.
Which version of Fred did you install? Were the patched for #2 already included? `if ( $ENV{HTTP_USER_AGENT} ) { ` does not work with Gazelle and the current _otobo.psgi_.

Best regards,
   Bernhard

**Comment by svenoe** [comment]
Currently $ENV{HTTP_USER_AGENT} cannot be used in Kernel/Config/Files/AAAFred.pm I believe.

**Comment by stefanhaerter** [comment]
The changes included in #8 solve the problem, thus I included them into the current code. Closing the issue.
